const jobData = {
    "Finance": {
        description: "The finance industry encompasses a wide range of financial services, including banking, investments, insurance, and financial planning. Professionals in this industry play a crucial role in managing funds, mitigating risks, and facilitating economic growth. From financial analysts and investment bankers to insurance agents and wealth managers, the finance sector offers diverse career opportunities for individuals with strong analytical skills, attention to detail, and a keen understanding of market dynamics. With globalization and technological advancements shaping the financial landscape, professionals in this field must adapt to evolving regulations, market trends, and customer preferences.",
        advice: "Entering the finance industry requires a solid educational foundation in finance, economics, accounting, or a related field. Pursuing internships, co-op programs, or entry-level positions at financial institutions can provide valuable hands-on experience and industry exposure. Obtaining relevant certifications such as the Chartered Financial Analyst (CFA), Certified Financial Planner (CFP), or Chartered Financial Consultant (ChFC) can enhance credibility and career prospects. Developing strong quantitative skills, proficiency in financial modeling, and knowledge of financial software tools are essential for success in finance roles. Networking with professionals in the industry, staying updated on market trends, and seeking mentorship can provide valuable insights and career guidance. Additionally, cultivating ethical conduct, integrity, and client-focused communication skills is crucial for building trust and credibility in the finance profession."
      },
      "Education": {
        description: "The education industry plays a pivotal role in shaping the minds and futures of individuals through the impartation of knowledge, skills, and values. Professionals in this field are dedicated to facilitating learning, fostering personal growth, and preparing students for academic success and lifelong learning. From teachers and professors to educational administrators and counselors, the education sector offers diverse career pathways and opportunities for individuals passionate about making a positive impact on society through education. With advancements in technology, pedagogy, and educational research, educators must adapt to evolving teaching methods, student needs, and educational standards.",
        advice: "Embarking on a career in education requires a strong commitment to lifelong learning, personal growth, and professional development. Aspiring educators should pursue a relevant degree or certification in education, teaching, or a specific subject area, depending on their career goals and interests. Gaining practical experience through student teaching, tutoring, or educational internships can provide valuable hands-on exposure to classroom dynamics and instructional strategies. Continuing education through workshops, seminars, or graduate studies can enhance teaching skills and subject knowledge. Building strong relationships with students, colleagues, and parents through effective communication, empathy, and cultural competence is essential for creating a supportive learning environment. Additionally, staying updated on educational trends, technology integration, and pedagogical research can enrich teaching practices and student engagement."
      },
      "Engineering": {
        description: "Engineering is a diverse and dynamic field that encompasses the application of scientific principles and mathematical methods to design, develop, and maintain complex systems, structures, and processes. From civil and mechanical engineering to electrical, chemical, and aerospace engineering, professionals in this field are involved in solving real-world problems, innovating new technologies, and improving the quality of life for society. Engineering disciplines vary widely in scope and specialization, ranging from traditional fields such as civil engineering and mechanical engineering to emerging areas such as biomedical engineering and sustainable energy systems.",
        advice: "To pursue a career in engineering, aspiring professionals should pursue a degree in engineering or a related field, such as physics or mathematics, from an accredited institution. Gaining practical experience through internships, co-op programs, or research projects can provide valuable hands-on exposure to engineering practices and industry standards. Developing strong analytical, problem-solving, and critical-thinking skills is essential for tackling complex engineering challenges. Building a solid foundation in mathematics, physics, and computer science is crucial for understanding engineering principles and applying them to real-world problems. Pursuing professional licensure or certification in a specific engineering discipline can enhance career prospects and credibility within the industry. Networking with professionals, participating in engineering societies, and attending industry conferences can provide valuable insights, mentorship, and career opportunities. Additionally, staying updated on technological advancements, industry trends, and best practices is essential for continuous learning and professional growth in the field of engineering."
      },
      "Marketing": {
        description: "The marketing industry encompasses a wide range of activities aimed at promoting products, services, or ideas to target audiences. It involves strategic planning, creative execution, and effective communication to drive consumer engagement, brand awareness, and sales growth. From digital marketing and social media management to market research and advertising, professionals in this field employ various techniques and platforms to reach and influence consumers in today's competitive marketplace. With the advent of digital technologies and social media platforms, the marketing landscape has evolved rapidly, presenting new challenges and opportunities for marketers.",
        advice: "Entering the marketing industry requires a combination of creativity, analytical skills, and strategic thinking. Aspiring marketers should pursue a degree in marketing, communications, business administration, or a related field to acquire foundational knowledge and skills. Gaining practical experience through internships, co-op programs, or entry-level positions at marketing agencies or companies can provide valuable industry exposure and hands-on experience. Developing proficiency in digital marketing tools, analytics platforms, and social media channels is essential for success in modern marketing roles. Building a strong portfolio of marketing campaigns, projects, or case studies can showcase skills and expertise to potential employers. Networking with professionals in the industry, attending marketing conferences, and participating in industry events can facilitate career growth and advancement. Additionally, staying updated on industry trends, consumer behavior, and emerging technologies is crucial for staying ahead in the fast-paced and ever-changing field of marketing."
      },
      "Hospitality": {
        description: "The hospitality industry encompasses a wide range of businesses and services focused on providing accommodations, dining experiences, and entertainment to travelers and guests. From hotels and restaurants to resorts, cruise lines, and event planning companies, professionals in this field are dedicated to creating memorable experiences and ensuring guest satisfaction. The hospitality industry is characterized by its focus on customer service, attention to detail, and commitment to delivering exceptional experiences.",
        advice: "Embarking on a career in hospitality requires a passion for service, strong interpersonal skills, and a commitment to excellence. Aspiring professionals should pursue a degree or certification in hospitality management, tourism, or a related field to acquire foundational knowledge and skills. Gaining practical experience through internships, co-op programs, or entry-level positions at hotels, restaurants, or event venues can provide valuable hands-on experience and industry exposure. Developing strong communication, problem-solving, and leadership skills is essential for success in hospitality roles. Building a network of industry contacts, mentors, and peers can provide valuable insights, guidance, and career opportunities within the hospitality field. Additionally, staying updated on industry trends, customer preferences, and best practices is crucial for delivering exceptional guest experiences and maintaining a competitive edge in the hospitality industry."
      },
      "Human Resources": {
        description: "The human resources (HR) industry is responsible for managing an organization's most valuable asset—its people. HR professionals play a critical role in recruiting, hiring, training, and retaining employees, as well as ensuring compliance with employment laws and regulations. From talent acquisition and employee relations to compensation and benefits administration, HR encompasses a broad spectrum of functions aimed at supporting organizational goals and fostering a positive work environment.",
        advice: "Embarking on a career in human resources requires a combination of interpersonal skills, organizational acumen, and a commitment to fostering a positive workplace culture. Aspiring HR professionals should pursue a degree or certification in human resources management, business administration, psychology, or a related field to acquire foundational knowledge and skills. Gaining practical experience through internships, co-op programs, or entry-level HR positions can provide valuable hands-on experience and industry exposure. Developing strong communication, negotiation, and conflict-resolution skills is essential for success in HR roles. Building a solid understanding of employment laws, regulations, and best practices is crucial for ensuring compliance and mitigating risks. Networking with HR professionals, attending industry conferences, and participating in professional associations can provide valuable insights, mentorship, and career opportunities within the HR field. Additionally, staying updated on industry trends, technological advancements, and emerging HR practices is essential for staying ahead in the dynamic and evolving field of human resources."
      },
      "Retail": {
        description: "The retail industry encompasses a wide range of businesses involved in the sale of goods and services to consumers. From brick-and-mortar stores and online retailers to supermarkets, specialty shops, and department stores, retail plays a vital role in the economy and consumer marketplace. Retail professionals are responsible for various functions, including merchandising, sales, customer service, inventory management, and store operations.",
        advice: "Entering the retail industry requires a passion for customer service, strong communication skills, and a commitment to delivering exceptional shopping experiences. Aspiring retail professionals should pursue opportunities for hands-on experience through internships, co-op programs, or entry-level positions at retail stores or companies. Developing skills in sales techniques, product knowledge, and customer relationship management is essential for success in retail roles. Building a strong work ethic, attention to detail, and problem-solving skills can contribute to success in a fast-paced retail environment. Networking with industry professionals, attending retail conferences, and staying updated on industry trends can provide valuable insights, guidance, and career opportunities within the retail field. Additionally, embracing digital technologies and omnichannel retail strategies can help retailers adapt to changing consumer preferences and market dynamics."
      },
      "Law": {
        description: "The legal industry encompasses a diverse range of professions and practice areas dedicated to upholding justice, resolving disputes, and protecting individual rights and freedoms. From lawyers and judges to paralegals, legal assistants, and legal consultants, professionals in this field play a critical role in interpreting and applying laws, advocating for clients, and ensuring access to legal representation. The legal industry is characterized by its commitment to upholding ethical standards, promoting fairness, and safeguarding the rule of law.",
        advice: "Pursuing a career in law requires a strong commitment to justice, critical thinking, and advocacy. Aspiring legal professionals should pursue a degree in law from an accredited institution and pass the bar exam in their jurisdiction to become licensed to practice law. Gaining practical experience through internships, clerkships, or legal clinics can provide valuable hands-on exposure to legal practice and courtroom procedures. Developing strong research, writing, and oral advocacy skills is essential for success in legal roles. Building a professional network of mentors, colleagues, and industry contacts can provide valuable guidance, support, and career opportunities within the legal field. Staying updated on changes in laws, regulations, and legal precedents through continuing education and professional development is crucial for maintaining competence and ethical practice. Additionally, cultivating integrity, empathy, and a commitment to serving the public interest are essential for earning trust and credibility as a legal professional."
      },
      "Construction": {
        description: "The construction industry encompasses a wide range of activities related to the design, development, and construction of buildings, infrastructure, and civil works projects. From residential and commercial construction to infrastructure development and industrial projects, professionals in this field are responsible for bringing architectural designs to life, ensuring structural integrity, and delivering projects on time and within budget. The construction industry plays a vital role in driving economic growth, creating jobs, and shaping the built environment.",
        advice: "Embarking on a career in construction requires a combination of technical skills, practical experience, and a commitment to safety and quality. Aspiring construction professionals should pursue a degree or certification in construction management, engineering, architecture, or a related field to acquire foundational knowledge and skills. Gaining hands-on experience through internships, apprenticeships, or entry-level positions with construction companies or contractors can provide valuable exposure to construction practices and industry standards. Developing proficiency in construction techniques, project management tools, and safety protocols is essential for success in construction roles. Building strong communication, teamwork, and problem-solving skills can contribute to effective collaboration and project delivery. Networking with professionals in the industry, participating in construction associations, and attending industry events can provide valuable insights, mentorship, and career opportunities within the construction field. Additionally, staying updated on industry trends, technological advancements, and best practices is crucial for staying ahead in the competitive and dynamic field of construction."
      },
      "Art and Design": {
        description: "The art and design industry encompasses a diverse range of creative disciplines and professions dedicated to expressing ideas, emotions, and aesthetics through visual, auditory, and tactile mediums. From fine arts and graphic design to fashion, interior design, and multimedia production, professionals in this field play a vital role in shaping culture, inspiring creativity, and communicating messages through art and design. The art and design industry is characterized by its emphasis on innovation, self-expression, and exploration of diverse artistic styles and techniques.",
        advice: "Pursuing a career in art and design requires a passion for creativity, a keen eye for detail, and a commitment to self-expression. Aspiring artists and designers should cultivate their artistic skills and develop a strong portfolio showcasing their work in various mediums and styles. Pursuing formal education in art, design, or a related field from accredited institutions or art schools can provide foundational knowledge and technical skills. Gaining practical experience through internships, apprenticeships, or freelance projects can provide valuable industry exposure and networking opportunities. Building a professional network of peers, mentors, and industry contacts can provide support, guidance, and career opportunities within the art and design field. Staying updated on artistic trends, technological advancements, and emerging mediums or techniques is essential for staying relevant and competitive in the ever-evolving art and design industry."
      }, "Information Technology": {
        description: "The information technology (IT) industry is focused on the development, implementation, and maintenance of computer systems, software, and networks. IT professionals work in various areas, including software development, cybersecurity, network administration, and IT support. This industry plays a crucial role in driving innovation, improving efficiency, and ensuring the security of digital infrastructure.",
        advice: "Aspiring IT professionals should pursue a degree in computer science, information technology, or a related field. Gaining practical experience through internships, co-op programs, or entry-level positions is essential. Obtaining certifications such as CompTIA A+, Cisco Certified Network Associate (CCNA), or Certified Information Systems Security Professional (CISSP) can enhance career prospects. Staying updated on technological advancements and continuously improving coding and technical skills are crucial for success in IT roles."
    },
    "Media and Communications": {
        description: "The media and communications industry encompasses a broad range of professions involved in creating, disseminating, and managing information and entertainment content. This includes journalism, public relations, advertising, broadcasting, and digital media. Professionals in this field play a key role in shaping public opinion, promoting brands, and delivering news and entertainment to audiences.",
        advice: "Pursuing a degree in journalism, communications, media studies, or a related field is beneficial. Gaining experience through internships, campus media, or freelance work can provide valuable exposure. Developing strong writing, editing, and multimedia skills is crucial. Networking with industry professionals, attending media conferences, and staying updated on media trends and technologies can enhance career opportunities."
    },
    "Logistics and Supply Chain Management": {
        description: "The logistics and supply chain management industry involves the planning, implementation, and control of the movement and storage of goods, services, and information from origin to consumption. Professionals in this field ensure efficient and effective supply chain operations, encompassing transportation, warehousing, inventory management, and procurement.",
        advice: "A degree in supply chain management, logistics, or business administration is advantageous. Practical experience through internships, co-op programs, or entry-level positions is essential. Developing strong analytical, problem-solving, and organizational skills is crucial. Obtaining certifications such as Certified Supply Chain Professional (CSCP) or Certified Professional in Supply Management (CPSM) can enhance career prospects. Staying updated on industry trends and technological advancements in logistics is also important."
    },
    "Energy and Utilities": {
        description: "The energy and utilities industry encompasses the production, distribution, and management of energy resources, including oil, natural gas, coal, nuclear, and renewable energy sources. Professionals in this field work to ensure a reliable and sustainable energy supply, develop new energy technologies, and address environmental and regulatory challenges.",
        advice: "A degree in engineering, environmental science, or energy management is beneficial. Gaining practical experience through internships, co-op programs, or entry-level positions is important. Developing strong analytical, problem-solving, and technical skills is essential. Networking with industry professionals, participating in energy associations, and staying updated on energy policies and technological advancements can enhance career opportunities."
    },
    "Manufacturing": {
        description: "The manufacturing industry involves the production of goods using raw materials, machinery, and labor. This industry encompasses various sectors, including automotive, electronics, pharmaceuticals, and consumer goods. Professionals in manufacturing focus on improving production efficiency, quality control, and innovation in product design and processes.",
        advice: "A degree in manufacturing engineering, industrial engineering, or a related field is advantageous. Practical experience through internships, co-op programs, or entry-level positions is essential. Developing strong technical, problem-solving, and project management skills is crucial. Obtaining certifications such as Six Sigma or Lean Manufacturing can enhance career prospects. Staying updated on industry trends and advancements in manufacturing technologies is also important."
    },
    "Aerospace": {
        description: "The aerospace industry involves the design, development, and production of aircraft, spacecraft, and related systems and equipment. Professionals in this field work on various aspects of aerospace engineering, including aerodynamics, propulsion, avionics, and materials science. The industry plays a critical role in advancing aviation and space exploration technologies.",
        advice: "Pursuing a degree in aerospace engineering, mechanical engineering, or a related field is beneficial. Practical experience through internships, co-op programs, or entry-level positions is essential. Developing strong analytical, problem-solving, and technical skills is crucial. Obtaining certifications such as Professional Engineer (PE) in aerospace can enhance career prospects. Staying updated on industry trends and advancements in aerospace technologies is also important."
    },
    "Biotechnology": {
        description: "The biotechnology industry focuses on the use of biological processes and organisms to develop products and technologies for healthcare, agriculture, and environmental sustainability. Professionals in this field work on genetic engineering, drug development, biofuels, and other innovative applications of biotechnology.",
        advice: "A degree in biotechnology, molecular biology, or a related field is advantageous. Practical experience through internships, co-op programs, or research projects is essential. Developing strong laboratory, analytical, and problem-solving skills is crucial. Networking with industry professionals, attending biotechnology conferences, and staying updated on scientific advancements can enhance career opportunities."
    },
    "Environmental Science and Sustainability": {
        description: "The environmental science and sustainability industry focuses on understanding and addressing environmental issues, promoting sustainable practices, and conserving natural resources. Professionals in this field work on environmental protection, renewable energy, waste management, and sustainability planning.",
        advice: "Pursuing a degree in environmental science, sustainability, or a related field is beneficial. Practical experience through internships, co-op programs, or entry-level positions is essential. Developing strong analytical, research, and problem-solving skills is crucial. Obtaining certifications such as LEED (Leadership in Energy and Environmental Design) can enhance career prospects. Staying updated on environmental policies and advancements in sustainability practices is also important."
    },
    "Agriculture and Food Science": {
        description: "The agriculture and food science industry involves the study, cultivation, and processing of food and other agricultural products. Professionals in this field work on improving agricultural practices, developing new food products, and ensuring food safety and sustainability.",
        advice: "A degree in agriculture, food science, or a related field is advantageous. Practical experience through internships, co-op programs, or research projects is essential. Developing strong analytical, problem-solving, and technical skills is crucial. Networking with industry professionals, attending agricultural conferences, and staying updated on advancements in agricultural technologies can enhance career opportunities."
    },
    "Automotive": {
        description: "The automotive industry encompasses the design, development, manufacturing, and marketing of motor vehicles. Professionals in this field work on vehicle engineering, production, quality control, and sales and marketing. The industry plays a vital role in transportation and economic growth.",
        advice: "Pursuing a degree in automotive engineering, mechanical engineering, or a related field is beneficial. Practical experience through internships, co-op programs, or entry-level positions is essential. Developing strong technical, problem-solving, and project management skills is crucial. Obtaining certifications such as ASE (Automotive Service Excellence) can enhance career prospects. Staying updated on industry trends and advancements in automotive technologies is also important."
    },
    "Telecommunications": {
        description: "The telecommunications industry focuses on the transmission of information over distances through electronic means. This includes telephone, internet, and satellite communications. Professionals in this field work on network infrastructure, wireless communications, and data transmission technologies.",
        advice: "A degree in telecommunications, electrical engineering, or a related field is advantageous. Practical experience through internships, co-op programs, or entry-level positions is essential. Developing strong technical, analytical, and problem-solving skills is crucial. Obtaining certifications such as Cisco Certified Network Professional (CCNP) can enhance career prospects. Staying updated on industry trends and advancements in telecommunications technologies is also important."
    },
    "Information Technology": {
        description: "The information technology (IT) industry is focused on the development, implementation, and maintenance of computer systems, software, and networks. IT professionals work in various areas, including software development, cybersecurity, network administration, and IT support. This industry plays a crucial role in driving innovation, improving efficiency, and ensuring the security of digital infrastructure.",
        advice: "Aspiring IT professionals should pursue a degree in computer science, information technology, or a related field. Gaining practical experience through internships, co-op programs, or entry-level positions is essential. Obtaining certifications such as CompTIA A+, Cisco Certified Network Associate (CCNA), or Certified Information Systems Security Professional (CISSP) can enhance career prospects. Staying updated on technological advancements and continuously improving coding and technical skills are crucial for success in IT roles."
    },
    "Media and Communications": {
        description: "The media and communications industry encompasses a broad range of professions involved in creating, disseminating, and managing information and entertainment content. This includes journalism, public relations, advertising, broadcasting, and digital media. Professionals in this field play a key role in shaping public opinion, promoting brands, and delivering news and entertainment to audiences.",
        advice: "Pursuing a degree in journalism, communications, media studies, or a related field is beneficial. Gaining experience through internships, campus media, or freelance work can provide valuable exposure. Developing strong writing, editing, and multimedia skills is crucial. Networking with industry professionals, attending media conferences, and staying updated on media trends and technologies can enhance career opportunities."
    },
    "Logistics and Supply Chain Management": {
        description: "The logistics and supply chain management industry involves the planning, implementation, and control of the movement and storage of goods, services, and information from origin to consumption. Professionals in this field ensure efficient and effective supply chain operations, encompassing transportation, warehousing, inventory management, and procurement.",
        advice: "A degree in supply chain management, logistics, or business administration is advantageous. Practical experience through internships, co-op programs, or entry-level positions is essential. Developing strong analytical, problem-solving, and organizational skills is crucial. Obtaining certifications such as Certified Supply Chain Professional (CSCP) or Certified Professional in Supply Management (CPSM) can enhance career prospects. Staying updated on industry trends and technological advancements in logistics is also important."
    },
    "Energy and Utilities": {
        description: "The energy and utilities industry encompasses the production, distribution, and management of energy resources, including oil, natural gas, coal, nuclear, and renewable energy sources. Professionals in this field work to ensure a reliable and sustainable energy supply, develop new energy technologies, and address environmental and regulatory challenges.",
        advice: "A degree in engineering, environmental science, or energy management is beneficial. Gaining practical experience through internships, co-op programs, or entry-level positions is important. Developing strong analytical, problem-solving, and technical skills is essential. Networking with industry professionals, participating in energy associations, and staying updated on energy policies and technological advancements can enhance career opportunities."
    },
    "Manufacturing": {
        description: "The manufacturing industry involves the production of goods using raw materials, machinery, and labor. This industry encompasses various sectors, including automotive, electronics, pharmaceuticals, and consumer goods. Professionals in manufacturing focus on improving production efficiency, quality control, and innovation in product design and processes.",
        advice: "A degree in manufacturing engineering, industrial engineering, or a related field is advantageous. Practical experience through internships, co-op programs, or entry-level positions is essential. Developing strong technical, problem-solving, and project management skills is crucial. Obtaining certifications such as Six Sigma or Lean Manufacturing can enhance career prospects. Staying updated on industry trends and advancements in manufacturing technologies is also important."
    },
    "Aerospace": {
        description: "The aerospace industry involves the design, development, and production of aircraft, spacecraft, and related systems and equipment. Professionals in this field work on various aspects of aerospace engineering, including aerodynamics, propulsion, avionics, and materials science. The industry plays a critical role in advancing aviation and space exploration technologies.",
        advice: "Pursuing a degree in aerospace engineering, mechanical engineering, or a related field is beneficial. Practical experience through internships, co-op programs, or entry-level positions is essential. Developing strong analytical, problem-solving, and technical skills is crucial. Obtaining certifications such as Professional Engineer (PE) in aerospace can enhance career prospects. Staying updated on industry trends and advancements in aerospace technologies is also important."
    },
    "Biotechnology": {
        description: "The biotechnology industry focuses on the use of biological processes and organisms to develop products and technologies for healthcare, agriculture, and environmental sustainability. Professionals in this field work on genetic engineering, drug development, biofuels, and other innovative applications of biotechnology.",
        advice: "A degree in biotechnology, molecular biology, or a related field is advantageous. Practical experience through internships, co-op programs, or research projects is essential. Developing strong laboratory, analytical, and problem-solving skills is crucial. Networking with industry professionals, attending biotechnology conferences, and staying updated on scientific advancements can enhance career opportunities."
    },
    "Environmental Science and Sustainability": {
        description: "The environmental science and sustainability industry focuses on understanding and addressing environmental issues, promoting sustainable practices, and conserving natural resources. Professionals in this field work on environmental protection, renewable energy, waste management, and sustainability planning.",
        advice: "Pursuing a degree in environmental science, sustainability, or a related field is beneficial. Practical experience through internships, co-op programs, or entry-level positions is essential. Developing strong analytical, research, and problem-solving skills is crucial. Obtaining certifications such as LEED (Leadership in Energy and Environmental Design) can enhance career prospects. Staying updated on environmental policies and advancements in sustainability practices is also important."
    },
    "Agriculture and Food Science": {
        description: "The agriculture and food science industry involves the study, cultivation, and processing of food and other agricultural products. Professionals in this field work on improving agricultural practices, developing new food products, and ensuring food safety and sustainability.",
        advice: "A degree in agriculture, food science, or a related field is advantageous. Practical experience through internships, co-op programs, or research projects is essential. Developing strong analytical, problem-solving, and technical skills is crucial. Networking with industry professionals, attending agricultural conferences, and staying updated on advancements in agricultural technologies can enhance career opportunities."
    },
    "Automotive": {
        description: "The automotive industry encompasses the design, development, manufacturing, and marketing of motor vehicles. Professionals in this field work on vehicle engineering, production, quality control, and sales and marketing. The industry plays a vital role in transportation and economic growth.",
        advice: "Pursuing a degree in automotive engineering, mechanical engineering, or a related field is beneficial. Practical experience through internships, co-op programs, or entry-level positions is essential. Developing strong technical, problem-solving, and project management skills is crucial. Obtaining certifications such as ASE (Automotive Service Excellence) can enhance career prospects. Staying updated on industry trends and advancements in automotive technologies is also important."
    },
    "Telecommunications": {
        description: "The telecommunications industry focuses on the transmission of information over distances through electronic means. This includes telephone, internet, and satellite communications. Professionals in this field work on network infrastructure, wireless communications, and data transmission technologies.",
        advice: "A degree in telecommunications, electrical engineering, or a related field is advantageous. Practical experience through internships, co-op programs, or entry-level positions is essential. Developing strong technical, analytical, and problem-solving skills is crucial. Obtaining certifications such as Cisco Certified Network Professional (CCNP) can enhance career prospects. Staying updated on industry trends and advancements in telecommunications technologies is also important."
    }
};

const jobTitles = Object.keys(jobData);

function displayResults(query) {
    const resultsDiv = document.getElementById("results");
    resultsDiv.innerHTML = ""; 


    const matchingJobs = jobTitles.filter(title => title.toLowerCase().includes(query.toLowerCase()));

  
    matchingJobs.forEach(job => {
        const resultDiv = document.createElement("div");
        resultDiv.classList.add("result");

        const titleElement = document.createElement("h2");
        titleElement.textContent = job;
        resultDiv.appendChild(titleElement);

        const descriptionElement = document.createElement("p");
        descriptionElement.textContent = jobData[job].description;
        resultDiv.appendChild(descriptionElement);

        const adviceElement = document.createElement("p");
        adviceElement.textContent = "Advice: " + jobData[job].advice;
        resultDiv.appendChild(adviceElement);

        resultsDiv.appendChild(resultDiv);
    });
}


function handleInput() {
    const query = this.value.toLowerCase();
    const autocompleteDiv = document.getElementById("autocomplete");
    const autocompleteSuggestions = jobTitles.filter(title => title.toLowerCase().startsWith(query));

    autocompleteDiv.innerHTML = autocompleteSuggestions.map(suggestion => `<div>${suggestion}</div>`).join('');

    if (query) {
        displayResults(query);
    } else {
        document.getElementById("results").innerHTML = "";
    }
}

function handleAutocompleteClick(event) {
    const searchInput = document.getElementById("searchInput");
    if (event.target.tagName === "DIV") {
        searchInput.value = event.target.textContent;
        displayResults(event.target.textContent);
        document.getElementById("autocomplete").innerHTML = "";
    }
}

document.getElementById("searchInput").addEventListener("input", handleInput);
document.getElementById("autocomplete").addEventListener("click", handleAutocompleteClick);
